site_name: ETJump Documentation
nav:
- 'Getting Started': index.md
- 'Client':
  - 'ETJump CVars': 'client/etjump_cvars.md'
  - 'ETMain CVars': 'client/etmain_cvars.md'
  - 'Client Commands': 'client/client_commands.md'
- 'Server':
  - 'Server CVars': 'server/server_cvars.md'
  - 'Server Admin System': 'server/admin_system.md'
  - 'Setting Up Server': 'server/server_setup.md'
- 'Mapping':
  - 'ETJump Mapping': 'mapping/getting_started.md'
  - 'ETJump Entities': 'mapping/mapping_entities.md'
  - 'ETJump Map Scripting': 'mapping/mapscripting.md'
theme: readthedocs
repo_url: https://github.com/etjump/documentation